### ISSUE TITLE
Possibility to pass color option for Vimeo videos

### ISSUE THREAD

**Issue by belkin** [vigetlabs/craft-videoembed#7]
Hi there!

I would like to pass a color option for Vimeo videos. 

Something like that:
https://player.vimeo.com/video/235215203?color=f9c716

**Comment by davist11** [comment]
You should be able to handle that in your Twig templates. You can take the embed URL and add a query string to it.

**Comment by belkin** [comment]
Oh yeah .. I don't know where I was looking. Thanks! 👍
